### ISSUE TITLE
push.html

### ISSUE THREAD

**Issue by maxPugh** [jay-hinds/arrayMethods#1]
Just something little I noticed while looking through your push.html code

Line 35:

`for (var i = arrayIndex; i < arguments.length + 1; i++) {`

If arrayIndex > arguments.length then the for loop will not run.

Therefore:
```
var testArray = [1,2,3,4,5];
var result = push(testArray, 6, 7)
console.log(testArray);
console.log(result)
```
Will give:
```
[1,2,3,4,5]
5
```

**Comment by hindsjay** [comment]
ah yes, I see that.  I updated the code to cover this and added another test to confirm.
Thanks!
